config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}

  root 'home#index'
  get '/home/index'
  get '/home/about'

  resources :posts, :except => [:index] do
    collection do
      get 'list/:id' => 'posts#list', as: 'list'
    end
    resources :comments, module: :posts, shallow: true
  end

  resources :playgrounds, :except => [:index] do
    collection do
      resources :ideas, :except => [:index] do
        collection do
          get 'list/:id' => 'ideas#list', as: 'list'
        end
        resources :comments, module: :ideas, shallow: true
      end

      resources :scraps, :except => [:index] do
        collection do
          get 'list/:id' => 'scraps#list', as: 'list'
          get 'members/:id' => 'scraps#members', as: 'members'
        end
        get 'team/:id' => 'scraps#team', as: 'team'
        resources :comments, module: :scraps, shallow: true
      end

      get 'friends'
      get 'list/:id' => 'playgrounds#list', as: 'list'
    end
    resources :comments, module: :playgrounds, shallow: true
  end

end

app/models/playground.rb
class Playground < ActiveRecord::Base

	belongs_to :user
	has_many :comments, as: :commentable, dependent: :destroy

	validates :title, :presence => true
	validates :context, :presence => true

end

app/controllers/playgrounds/comments_controller.rb
class Playgrounds::CommentsController < CommentsController
	before_action :set_commentable, only: [:create]
	private
		def set_commentable
			@commentable = Playground.find(params[:playground_id])
		end
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController

	before_action :authenticate_user!, except: [:friends, :list, :show]
	before_action :is_member, except: [:friends, :list, :show]

	def friends

    @members = Hash.new
    @counts = Hash.new
    @counts['ideas'], @counts['scraps'] = Array.new, Array.new

    (1..7).each do |x|
      @members[x.to_s] = User.where(team: x.to_s)
      @counts['ideas'][x-1], @counts['scraps'][x-1] = 0, 0
      @members[x.to_s].each do |m|
        @counts['ideas'][x-1] += m.ideas.count
        @counts['scraps'][x-1] += m.scraps.count
      end
    end

	end

	def list
		@playground_all = Playground.order("created_at DESC")
    @playground = @playground_all.limit(10).offset(10*params[:id].to_i)
    @count = @playground_all.count
	end

	def show
  		@playground = Playground.find(params[:id])
  		@playground.hits+=1
   	@playground.save
  end

  def new

  	@playground = Playground.new

  end

  def create

  	playground = Playground.new
  	playground.user = current_user
  	playground.title = params[:playground][:title]
  	playground.context = params[:playground][:context]
  	playground.save

  	redirect_to playground_path(playground.id)

  end

  def edit

  	@playground = Playground.find(params[:id])

  end

  def update

  	playground = Playground.find(params[:id])
  	playground.title = params[:playground][:title]
  	playground.context = params[:playground][:context]
  	playground.save

  	redirect_to playground_path(playground.id)

  end

  def destroy

  	playground = Playground.find(params[:id])
  	playground.destroy

  	redirect_to list_playgrounds_path(0)

  end

	private
		def is_member
			redirect_to root_path unless User.find(current_user.id).member
		end

end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/views/playgrounds/_header.html.erb
<header class="intro-header" style="background-image: url('<%= image_url('bg/playground.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>놀이터</h1>
                    <hr class="small">
                    <span class="subheading">여기서 만나요.</span>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/playgrounds/edit.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/playground-new.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>말 수정</h1>
                    <hr class="small">
                    <span class="subheading">아니, 그게 아니라.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container" style="text-align: center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= bootstrap_form_for(@playground, url: {action: "update"}, method: "put") do |f| %>
	            <div class="field">
	              <%= f.text_field :title, autofocus: true, label:"제목" %>
	            </div>

				<div class="field">
	              <%= f.text_area :context, label:"내용", style:"resize: none", rows: 15 %>
	            </div>

	            <div class="actions">
	              <%= f.submit "수정하기" %>
	            </div>
	        <% end %>
	    </div>
	</div>
</div>

app/views/playgrounds/friends.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<%= render "playgrounds/header"%>

<div class="container">
    <div class="row">
        <div id="tab" class="text-center">
            <div class="btn-group" role="group">
                <%= link_to '친구들', friends_playgrounds_path, class:"btn btn-default active" %>
                <%= link_to '자유롭게', list_playgrounds_path(0), class:"btn btn-default" %>
                <%= link_to '아이디어', list_ideas_path(0), class:"btn btn-default" %>
                <%= link_to '스크랩', list_scraps_path(0), class:"btn btn-default" %>

            </div>
        </div>
        <hr class="small light-gray">


        <div id="team" class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="each-team">
                <% @members.each do |hash, key| %>
                <h2><%= hash %>조</h2>
                <hr class="primary">
                <div class="row text-center">
                    <% key.each do |u| %>
                        <div class="col-lg-2 col-xs-4">
                            <div class="each-member">
                            <%= link_to members_scraps_path(u.id) do %>
                                <img src="<% if u.profile.url.nil? %><%= image_url('team/lion.png') %><% else %><%= u.profile.url %><% end %>" class="img-circle">
                                <%= u.name %>
                            <% end %>

                            </div>
                        </div>
                    <% end %>
                </div>

                <div class="progress">
                  <div class="progress-bar progress-bar-danger progress-idea" role="progressbar" aria-valuenow="<%= @counts['ideas'][hash.to_i-1] %>" aria-valuemin="0" aria-valuemax="1<%= @counts['ideas'].max %>" style="min-width: 4em; width: <% if @counts['ideas'][hash.to_i-1].nil? %>0<% else %><%= (@counts['ideas'][hash.to_i-1]*50).to_f/@counts['ideas'].max.to_f %><% end %>%;">
                    <c><%= @counts['ideas'][hash.to_i-1] %>개</c><e>아이디어</e>
                  </div>
                  <%= link_to scrap_team_path(hash.to_i,0) do %>
                    <div class="progress-bar progress-bar-warning progress-scrap" role="progressbar" aria-valuenow="<%= @counts['scraps'][hash.to_i-1] %>" aria-valuemin="0" aria-valuemax="<%= @counts['scraps'].max %>" style="min-width: 4em; width: <% if @counts['scraps'][hash.to_i-1].nil? %>0<% else %><%= (@counts['scraps'][hash.to_i-1]*50).to_f/@counts['scraps'].max.to_f %><% end %>%;">
                      <c><%= @counts['scraps'][hash.to_i-1] %>개</c><e>스크랩</e>
                    </div>
                  <% end %>
                </div>

                <% end %>
            </div>

        </div>
    </div>
</div>

app/views/playgrounds/list.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<%= render "playgrounds/header"%>

<div class="container">
    <div class="row">
        <div id="tab" class="text-center">
            <div class="btn-group" role="group">
                <%= link_to '친구들', friends_playgrounds_path, class:"btn btn-default" %>
                <%= link_to '자유롭게', list_playgrounds_path(0), class:"btn btn-default active" %>
                <%= link_to '아이디어', list_ideas_path(0), class:"btn btn-default" %>
                <%= link_to '스크랩', list_scraps_path(0), class:"btn btn-default" %>

            </div>
        </div>
        <hr class="small light-gray">

         <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="text-center">
                <%= "총 "+(((@count-1)/10)+1).to_s+"장 중, "+(params[:id].to_i+1).to_s+"번째 장"%>
            </div>
            <hr class="small second">
            <% @playground.each do |p| %>
            <div class="post-preview">
                <%= link_to playground_path(p.id) do %>
                    <h2 class="post-title">
                        <%= p.title %>
                    </h2>
                <% end %>
                <p class="post-meta"><%= link_to "#{p.user.name}", members_scraps_path(p.user.id), style:"font-style:normal" %> 말하다, <%= p.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일 %H시 %M분") %>, <%= p.hits %>번 읽힘. 댓글 <%= p.comments.count %>개.</p>
            </div>
            <hr>
            <% end %>

            <!-- Pager -->
            <ul class="pager">
                <%if params[:id].to_i>0%>
                    <li class="previous">
                        <%= link_to list_playgrounds_path(params[:id].to_i-1) do %>&larr; 이전<% end %>
                    </li>
                <% else %>
                    <li class="previous disabled">
                        <a>&larr; 이전</a>
                    </li>
                <% end %>

                <% if user_signed_in? %>
                  <% if current_user.member %>
                    <%= link_to '말하기', new_playground_path, class:"btn btn-default" %>
                  <% end %>
                <% end %>

                <%if params[:id].to_i==(@count-1)/10%>
                    <li class="next disabled">
                        <a>다음 &rarr;</a>
                    </li>
                <% else %>
                    <li class="next">
                        <%= link_to list_playgrounds_path(params[:id].to_i+1) do %>다음 &rarr;<% end %>
                    </li>
                <% end %>
            </ul>
        </div>





    </div>
</div>

app/views/playgrounds/new.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/playground-new.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>말하기</h1>
                    <hr class="small">
                    <span class="subheading">놀자. 친구들.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container" style="text-align: center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= bootstrap_form_for(@playground) do |f| %>
	            <div class="field">
	              <%= f.text_field :title, autofocus: true, label:"제목", :required => true %>
	            </div>


				<div class="field">
	              <%= f.text_area :context, label:"내용", style:"resize: none", rows: 15, :required => true %>
	            </div>

	            <div class="actions">
	              <%= f.submit "말하기" %>
	            </div>
	        <% end %>
	    </div>
	</div>
</div>

app/views/playgrounds/show.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/playground-show.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1><%= @playground.title %></h1>
                    <!-- <h2 class="subheading">  </h2> -->
                    <span class="meta"><%= link_to "#{@playground.user.name}", members_scraps_path(@playground.user.id), style:"font-style:normal" %> 말하다, <%= @playground.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일, %H시 %M분 %S초") %>, <%= @playground.hits %>번 읽힘.</span>
                    <br>
                    <% if user_signed_in? %>
                        <% if @playground.user.id == current_user.id %>
                            <%= form_tag edit_playground_path, method: "get" do %>
                                <button type="submit" class="btn btn-primary col-lg-2" style="margin: 2px">수정</button>
                            <% end %>
                            <%= form_tag playground_path, method: "delete" do %>
                                <button type="submit" class="btn btn-danger col-lg-2" style="margin: 2px" data-confirm="삭제하나요?">삭제</button>
                            <% end %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p style="padding-bottom: 30px">
                    <% unless @playground.context.nil? %>
                        <%= @playground.context.gsub("\r\n","<br>").html_safe %>
                    <% end %>
                </p>

                <hr>

                <div>
                    <% @playground.comments.each do |r|%>
                    <div class="row">
                        <div class="col-lg-8">
                            <h4><%= link_to "#{r.user.name}", members_scraps_path(r.user.id), style:"font-style:normal" %></h4>
                            <h6><%= r.updated_at.in_time_zone(9).strftime("%Y년 %m월 %d일, %H시 %M분 %S초")%></h6>
                            <p><%= r.context %></p>
                        </div>

                        <% if user_signed_in? %>
                            <% if r.user.id == current_user.id %>
                                <div class="col-lg-4">
                                    <%= form_tag comment_path(r.id), method: "delete" do %>
                                        <%= hidden_field_tag(:reply_id, r.id) %>
                                        <button type="submit" class="btn btn-danger" style="float:right; margin: 2px" data-confirm="삭제하나요?">삭제</button>
                                    <% end %>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                    <hr>
                    <% end %>
                </div>


                <div>
                    <%= bootstrap_form_for [@playground, @playground.comments.new] do |f| %>
                        <% if user_signed_in? %>
                            <div class="field">
                                <%= hidden_field_tag(:post_id, @playground.id) %>
                                <%= f.text_area :context, label: "댓글", style:"resize: none", rows: 4, :required => true %>
                            </div>
                        <% else %>
                            <fieldset disabled>
                                <div class="field">
                                    <%= hidden_field_tag(:post_id, @playground.id) %>
                                    <%= f.text_area :context, label: "댓글", style:"resize: none", rows: 4, :required => true%>
                                </div>
                            </fieldset>
                        <%end %>

                        <div class="actions">
                            <%= f.submit "댓글쓰기" %>
                        </div>
                    <% end %>

                </div>


            </div>

        </div>
    </div>
</article>