config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}

  root 'home#index'
  get '/home/index'
  get '/home/about'

  resources :posts, :except => [:index] do
    collection do
      get 'list/:id' => 'posts#list', as: 'list'
    end
    resources :comments, module: :posts, shallow: true
  end

  resources :playgrounds, :except => [:index] do
    collection do
      resources :ideas, :except => [:index] do
        collection do
          get 'list/:id' => 'ideas#list', as: 'list'
        end
        resources :comments, module: :ideas, shallow: true
      end

      resources :scraps, :except => [:index] do
        collection do
          get 'list/:id' => 'scraps#list', as: 'list'
          get 'members/:id' => 'scraps#members', as: 'members'
        end
        get 'team/:id' => 'scraps#team', as: 'team'
        resources :comments, module: :scraps, shallow: true
      end

      get 'friends'
      get 'list/:id' => 'playgrounds#list', as: 'list'
    end
    resources :comments, module: :playgrounds, shallow: true
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base

	belongs_to :user
	has_many :comments, as: :commentable, dependent: :destroy

	validates :title, :presence => true
	validates :context, :presence => true

end

app/controllers/ideas/comments_controller.rb
class Ideas::CommentsController < CommentsController
	before_action :set_commentable, only: [:create]
	private
		def set_commentable
			@commentable = Idea.find(params[:idea_id])
		end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

	before_action :authenticate_user!, except: [:list, :show]
  before_action :is_member, except: [:list, :show]

	def list
		@idea_all = Idea.order("created_at DESC")
    @idea = @idea_all.limit(10).offset(10*params[:id].to_i)
    @count = @idea_all.count
	end

	def show
  	@idea = Idea.find(params[:id])
    @idea.hits+=1
    @idea.save
  end

  def new

  	@idea = Idea.new

  end

  def create

  	idea = Idea.new
  	idea.user = current_user
  	idea.title = params[:idea][:title]
  	idea.context = params[:idea][:context]
  	idea.save

  	redirect_to idea_path(idea.id)

  end

  def edit

  	@idea = Idea.find(params[:id])

  end

  def update

  	idea = Idea.find(params[:id])
  	idea.title = params[:idea][:title]
  	idea.context = params[:idea][:context]
  	idea.save

  	redirect_to idea_path(idea.id)

  end

  def destroy

  	idea = Idea.find(params[:id])
  	idea.destroy

  	redirect_to list_ideas_path(0)

  end

  private

      def is_member
        redirect_to root_path unless User.find(current_user.id).member
      end

end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/edit.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/idea-new.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>아이디어 수정</h1>
                    <hr class="small">
                    <span class="subheading">아, 그게 아니었어.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container" style="text-align: center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= bootstrap_form_for(@idea) do |f| %>
	            <div class="field">
	              <%= f.text_field :title, autofocus: true, label:"제목" %>
	            </div>

				<div class="field">
	              <%= f.text_area :context, label:"내용", style:"resize: none", rows: 15 %>
	            </div>

	            <div class="actions">
	              <%= f.submit "수정하기" %>
	            </div>
	        <% end %>
	    </div>
	</div>
</div>

app/views/ideas/list.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<%= render "playgrounds/header"%>

<div class="container">
    <div class="row">
        <div id="tab" class="text-center">
            <div class="btn-group" role="group">
                <%= link_to '친구들', friends_playgrounds_path, class:"btn btn-default" %>
                <%= link_to '자유롭게', list_playgrounds_path(0), class:"btn btn-default" %>
                <%= link_to '아이디어', list_ideas_path(0), class:"btn btn-default active" %>
                <%= link_to '스크랩', list_scraps_path(0), class:"btn btn-default" %>

            </div>
        </div>
        <hr class="small light-gray">

         <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="text-center">
                <%= "총 "+(((@count-1)/10)+1).to_s+"장 중, "+(params[:id].to_i+1).to_s+"번째 장"%>
            </div>
            <hr class="small third">
            <% @idea.each do |p| %>
            <div class="post-preview">
                <%= link_to idea_path(p.id) do %>
                    <h2 class="post-title">
                        <%= p.title %>
                    </h2>
                <% end %>
                <p class="post-meta"><%= link_to "#{p.user.name}", members_scraps_path(p.user.id), style:"font-style:normal" %> 아이디어, <%= p.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일 %H시 %M분") %>, <%= p.hits %>번 읽힘. 댓글 <%= p.comments.count %>개.</p>
            </div>
            <hr>
            <% end %>

            <!-- Pager -->
            <ul class="pager">
                <%if params[:id].to_i>0%>
                    <li class="previous">
                        <%= link_to list_ideas_path(params[:id].to_i-1) do %>&larr; 이전<% end %>
                    </li>
                <% else %>
                    <li class="previous disabled">
                        <a>&larr; 이전</a>
                    </li>
                <% end %>

                <% if user_signed_in? %>
                  <% if current_user.member %>
                    <%= link_to '새 아이디어', new_idea_path, class:"btn btn-default" %>
                  <% end %>
                <% end %>

                <%if params[:id].to_i==(@count-1)/10%>
                    <li class="next disabled">
                        <a>다음 &rarr;</a>
                    </li>
                <% else %>
                    <li class="next">
                        <%= link_to list_ideas_path(params[:id].to_i+1) do %>다음 &rarr;<% end %>
                    </li>
                <% end %>
            </ul>
        </div>





    </div>
</div>

app/views/ideas/new.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/idea-new.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>새 아이디어</h1>
                    <hr class="small">
                    <span class="subheading">아이디어? 아이디어!</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container" style="text-align: center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= bootstrap_form_for(@idea) do |f| %>
	            <div class="field">
	              <%= f.text_field :title, autofocus: true, label:"제목", :required => true %>
	            </div>

				<div class="field">
	              <%= f.text_area :context, label:"내용", style:"resize: none", rows: 15, :required => true %>
	            </div>

	            <div class="actions">
	              <%= f.submit "등록하기" %>
	            </div>
	        <% end %>
	    </div>
	</div>
</div>

app/views/ideas/show.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/idea-show.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1><%= @idea.title %></h1>
                    <!-- <h2 class="subheading">  </h2> -->
                    <span class="meta"><%= link_to "#{@idea.user.name}", members_scraps_path(@idea.user.id), style:"font-style:normal" %> 아이디어, <%= @idea.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일, %H시 %M분 %S초") %>, <%= @idea.hits %>번 읽힘.</span>
                    <br>
                    <% if user_signed_in? %>
                        <% if @idea.user.id == current_user.id %>
                            <%= form_tag edit_idea_path, method: "get" do %>
                                <button type="submit" class="btn btn-primary col-lg-2" style="margin: 2px">수정</button>
                            <% end %>
                            <%= form_tag idea_path, method: "delete" do %>
                                <button type="submit" class="btn btn-danger col-lg-2" style="margin: 2px" data-confirm="삭제하나요?">삭제</button>
                            <% end %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p style="padding-bottom: 30px">
                    <% unless @idea.context.nil? %>
                        <%= @idea.context.gsub("\r\n","<br>").html_safe %>
                    <% end %>
                </p>

                <hr>

                <div>
                    <% @idea.comments.each do |r|%>
                    <div class="row">
                        <div class="col-lg-8">
                            <h4><%= link_to "#{r.user.name}", members_scraps_path(r.user.id), style:"font-style:normal" %></h4>
                            <h6><%= r.updated_at.in_time_zone(9).strftime("%Y년 %m월 %d일, %H시 %M분 %S초")%></h6>
                            <p><%= r.context %></p>
                        </div>

                        <% if user_signed_in? %>
                            <% if r.user.id == current_user.id %>
                                <div class="col-lg-4">
                                    <%= form_tag comment_path(r.id), method: "delete" do %>
                                        <button type="submit" class="btn btn-danger" style="float:right; margin: 2px" data-confirm="삭제하나요?">삭제</button>
                                    <% end %>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                    <hr>
                    <% end %>
                </div>


                <div>
                    <%= bootstrap_form_for [@idea, @idea.comments.new] do |f| %>
                        <% if user_signed_in? %>
                            <div class="field">
                                <%= f.text_area :context, label: "댓글", style:"resize: none", rows: 4, :required => true %>
                            </div>
                        <% else %>
                            <fieldset disabled>
                                <div class="field">
                                    <%= f.text_area :context, label: "댓글", style:"resize: none", rows: 4, :required => true%>
                                </div>
                            </fieldset>
                        <%end %>

                        <div class="actions">
                            <%= f.submit "댓글쓰기" %>
                        </div>
                    <% end %>
                </div>


            </div>

        </div>
    </div>
</article>