config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}

  root 'home#index'
  get '/home/index'
  get '/home/about'

  resources :posts, :except => [:index] do
    collection do
      get 'list/:id' => 'posts#list', as: 'list'
    end
    resources :comments, module: :posts, shallow: true
  end

  resources :playgrounds, :except => [:index] do
    collection do
      resources :ideas, :except => [:index] do
        collection do
          get 'list/:id' => 'ideas#list', as: 'list'
        end
        resources :comments, module: :ideas, shallow: true
      end

      resources :scraps, :except => [:index] do
        collection do
          get 'list/:id' => 'scraps#list', as: 'list'
          get 'members/:id' => 'scraps#members', as: 'members'
        end
        get 'team/:id' => 'scraps#team', as: 'team'
        resources :comments, module: :scraps, shallow: true
      end

      get 'friends'
      get 'list/:id' => 'playgrounds#list', as: 'list'
    end
    resources :comments, module: :playgrounds, shallow: true
  end

end

app/models/scrap.rb
class Scrap < ActiveRecord::Base

	belongs_to :user
	has_many :comments, as: :commentable, dependent: :destroy

	validates :title, :presence => true
	validates :url, :presence => true

end

app/controllers/scraps/comments_controller.rb
class Scraps::CommentsController < CommentsController
	before_action :set_commentable, only: [:create]
	private
		def set_commentable
			@commentable = Scrap.find(params[:scrap_id])
		end
end

app/controllers/scraps_controller.rb
class ScrapsController < ApplicationController

	before_action :authenticate_user!, except: [:list, :team, :members, :show]
  before_action :is_member, except: [:list, :team, :members, :show]

	def list
		@scrap_all = Scrap.order("created_at DESC")
    @scrap = @scrap_all.limit(10).offset(10*params[:id].to_i)
    @count = @scrap_all.count
	end

	def team

		@team_name = params[:scrap_id].to_s+"조"

		@team_member = User.where(team: params[:scrap_id].to_s)

		@user_id = Array.new
		@team_member.each do |m|
			@user_id << m.id
		end
		@scrap_all = Scrap.where(user_id: @user_id)
		@scrap_all = @scrap_all.order("created_at DESC")

		@scrap = @scrap_all.limit(10).offset(10*params[:id].to_i)
		@count = @scrap_all.count

	end

	def members
		@user = User.find(params[:id])
		@scrap = @user.scraps.order("created_at DESC")
	end

	def show
  	@scrap = Scrap.find(params[:id])
    @scrap.hits+=1
    @scrap.save
  end

  def new

  	@scrap = Scrap.new

  end

  def create

  	scrap = Scrap.new
  	scrap.user = current_user
  	scrap.title = params[:scrap][:title]
  	scrap.url = params[:scrap][:url]
  	scrap.context = params[:scrap][:context]
  	scrap.save

  	redirect_to scrap_path(scrap.id)

  end

  def edit

  	@scrap = Scrap.find(params[:id])

  end

  def update

  	scrap = Scrap.find(params[:id])
  	scrap.title = params[:scrap][:title]
  	scrap.url = params[:scrap][:url]
  	scrap.context = params[:scrap][:context]
  	scrap.save

  	redirect_to scrap_path(scrap.id)

  end

  def destroy

  	scrap = Scrap.find(params[:id])
  	scrap.destroy

  	redirect_to members_scraps_path(scrap.user.id)

  end

    private

      def is_member
        redirect_to root_path unless User.find(current_user.id).member
      end

end

app/helpers/scraps_helper.rb
module ScrapsHelper
end

app/views/scraps/edit.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/scrap-new.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>스크랩 수정</h1>
                    <hr class="small">
                    <span class="subheading">이게 아니었다.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container" style="text-align: center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= bootstrap_form_for(@scrap) do |f| %>
	            <div class="field">
	              <%= f.text_field :title, autofocus: true, label:"제목" %>
	            </div>

	            <div class="field">
	              <%= f.text_field :url, label:"주소", :required => true %>
	            </div>

							<div class="field">
	              <%= f.text_area :context, label:"내용", style:"resize: none", rows: 15 %>
	            </div>

	            <div class="actions">
	              <%= f.submit "수정하기" %>
	            </div>
	        <% end %>
	    </div>
	</div>
</div>

app/views/scraps/list.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<%= render "playgrounds/header"%>

<div class="container">
    <div class="row">
        <div id="tab" class="text-center">
            <div class="btn-group" role="group">
                <%= link_to '친구들', friends_playgrounds_path, class:"btn btn-default" %>
                <%= link_to '자유롭게', list_playgrounds_path(0), class:"btn btn-default" %>
                <%= link_to '아이디어', list_ideas_path(0), class:"btn btn-default" %>
                <%= link_to '스크랩', list_scraps_path(0), class:"btn btn-default active" %>
            </div>
        </div>
        <hr class="small light-gray">

         <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="text-center">
                <%= "총 "+(((@count-1)/10)+1).to_s+"장 중, "+(params[:id].to_i+1).to_s+"번째 장"%>
            </div>
            <hr class="small third">
            <% @scrap.each do |p| %>
            <div class="post-preview">
                <%= link_to scrap_path(p.id) do %>
                    <h2 class="post-title">
                        <%= p.title %>
                    </h2>
                <% end %>
                <p class="post-meta"><%= link_to "#{p.user.name}", members_scraps_path(p.user.id), style:"font-style:normal" %> 스크랩하다, <%= p.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일 %H시 %M분") %>, <%= p.hits %>번 읽힘. 댓글 <%= p.comments.count %>개.</p>
            </div>
            <hr>
            <% end %>

            <!-- Pager -->
            <ul class="pager">
                <%if params[:id].to_i>0%>
                    <li class="previous">
                        <%= link_to list_scraps_path(params[:id].to_i-1) do %>&larr; 이전<% end %>
                    </li>
                <% else %>
                    <li class="previous disabled">
                        <a>&larr; 이전</a>
                    </li>
                <% end %>

                <%if params[:id].to_i==(@count-1)/10%>
                    <li class="next disabled">
                        <a>다음 &rarr;</a>
                    </li>
                <% else %>
                    <li class="next">
                        <%= link_to list_scraps_path(params[:id].to_i+1) do %>다음 &rarr;<% end %>
                    </li>
                <% end %>
            </ul>
        </div>





    </div>
</div>

app/views/scraps/members.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/scrap.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading" style="padding-top: 100px; padding-bottom: 50px;">
                    <img src="<% if @user.profile.url.nil? %><%= image_url('team/lion.png') %><% else %><%= @user.profile.url %><% end %>" width="220px" class="img-circle">
                    <hr class="small">
                    <span class="subheading"><%= @user.name %></span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">

         <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

         <% if user_signed_in? %>
            <% if current_user.id==@user.id && current_user.member %>
                <div class="text-center">
                    <%= link_to '스크랩하기', new_scrap_path, class:"btn btn-default" %>
                </div>
            <% end %>
          <% end %>

            <hr class="small light-gray">

            <% @scrap.each do |p| %>
            <div class="post-preview">
                <%= link_to scrap_path(p.id) do %>
                    <h2 class="post-title">
                        <%= p.title %>
                    </h2>
                <% end %>
                <p class="post-meta"><%= link_to "#{p.user.name}", members_scraps_path(p.id), style:"font-style:normal" %> 스크랩 하다, <%= p.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일 %H시 %M분") %>, <%= p.hits %>번 읽힘, 댓글 <%= p.comments.count %>개.</p>
            </div>
            <hr>
            <% end %>

        </div>





    </div>
</div>

app/views/scraps/new.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/idea-new.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>스크랩하기</h1>
                    <hr class="small">
                    <span class="subheading">아하하</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container" style="text-align: center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= bootstrap_form_for(@scrap) do |f| %>
	            <div class="field">
	              <%= f.text_field :title, autofocus: true, label:"제목", :required => true %>
	            </div>

	            <div class="field">
	              <%= f.text_field :url, label:"주소", :required => true, autocomplete: "off" %>
	            </div>

							<div class="field">
	              <%= f.text_area :context, label:"내용", style:"resize: none", rows: 15, :required => true %>
	            </div>

	            <div class="actions">
	              <%= f.submit "등록하기" %>
	            </div>
	        <% end %>
	    </div>
	</div>
</div>

app/views/scraps/show.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/scrap-show.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1><%= @scrap.title %></h1>
                    <!-- <h2 class="subheading">  </h2> -->
                    <span class="meta"><%= link_to "#{@scrap.user.name}", members_scraps_path(@scrap.user.id), style:"font-style:normal" %> 스크랩 하다, <%= @scrap.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일, %H시 %M분 %S초") %>, <%= @scrap.hits %>번 읽힘.</span>
                    <br>
                    <% if user_signed_in? %>
                        <% if @scrap.user.id == current_user.id %>
                            <%= form_tag new_scrap_path, method: "get" do %>
                                <button type="submit" class="btn btn-success col-lg-2" style="margin: 2px">스크랩하기</button>
                            <% end %>
                            <%= form_tag edit_scrap_path, method: "get" do %>
                                <button type="submit" class="btn btn-primary col-lg-2" style="margin: 2px">수정</button>
                            <% end %>
                            <%= form_tag scrap_path, method: "delete" do %>
                                <button type="submit" class="btn btn-danger col-lg-2" style="margin: 2px" data-confirm="삭제하나요?">삭제</button>
                            <% end %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

                <% unless @scrap.url.nil? %>
                    <%= link_to '스크랩 바로가기', @scrap.url, target: '_blank', class:"btn btn-default" %>
                <% end %>

                <p style="padding-bottom: 30px">
                    <% unless @scrap.context.nil? %>
                        <%= @scrap.context.gsub("\r\n","<br>").html_safe %>
                    <% end %>
                </p>

                <hr>

                <div>
                    <% @scrap.comments.each do |r|%>
                    <div class="row">
                        <div class="col-lg-8">
                            <h4><%= link_to "#{r.user.name}", members_scraps_path(r.user.id), style:"font-style:normal" %></h4>
                            <h6><%= r.updated_at.in_time_zone(9).strftime("%Y년 %m월 %d일, %H시 %M분 %S초")%></h6>
                            <p><%= r.context %></p>
                        </div>

                        <% if user_signed_in? %>
                            <% if r.user.id == current_user.id %>
                                <div class="col-lg-4">
                                    <%= form_tag comment_path(r.id), method: "delete" do %>
                                        <button type="submit" class="btn btn-danger" style="float:right; margin: 2px" data-confirm="삭제하나요?">삭제</button>
                                    <% end %>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                    <hr>
                    <% end %>
                </div>


                <div>
                    <%= bootstrap_form_for [@scrap, @scrap.comments.new] do |f| %>
                        <% if user_signed_in? %>
                            <div class="field">
                                <%= f.text_area :context, label: "댓글", style:"resize: none", rows: 4, :required => true %>
                            </div>
                        <% else %>
                            <fieldset disabled>
                                <div class="field">
                                    <%= f.text_area :context, label: "댓글", style:"resize: none", rows: 4, :required => true%>
                                </div>
                            </fieldset>
                        <%end %>

                        <div class="actions">
                            <%= f.submit "댓글쓰기" %>
                        </div>
                    <% end %>
                </div>


            </div>

        </div>
    </div>
</article>

app/views/scraps/team.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/scrap.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading" style="padding-top: 100px; padding-bottom: 50px;">
                    <h1>조별 스크랩</h1>
                    <hr class="small">
                    <span class="subheading"><%= @team_name %></span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">

      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
         <div class="text-center">
             <%= "총 "+(((@count-1)/10)+1).to_s+"장 중, "+(params[:id].to_i+1).to_s+"번째 장"%>
         </div>
         <hr class="small third">
         <% @scrap.each do |p| %>
         <div class="post-preview">
             <%= link_to scrap_path(p.id) do %>
                 <h2 class="post-title">
                     <%= p.title %>
                 </h2>
             <% end %>
             <p class="post-meta"><%= link_to "#{p.user.name}", members_scraps_path(p.user.id), style:"font-style:normal" %> 아이디어, <%= p.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일 %H시 %M분") %>, <%= p.hits %>번 읽힘. 댓글 <%= p.comments.count %>개.</p>
         </div>
         <hr>
         <% end %>

         <!-- Pager -->
         <ul class="pager">
             <%if params[:id].to_i>0%>
                 <li class="previous">
                     <%= link_to scrap_team_path(params[:scrap_id].to_i,params[:id].to_i-1) do %>&larr; 이전<% end %>
                 </li>
             <% else %>
                 <li class="previous disabled">
                     <a>&larr; 이전</a>
                 </li>
             <% end %>

             <%if params[:id].to_i==(@count-1)/10%>
                 <li class="next disabled">
                     <a>다음 &rarr;</a>
                 </li>
             <% else %>
                 <li class="next">
                     <%= link_to scrap_team_path(params[:scrap_id].to_i,params[:id].to_i+1) do %>다음 &rarr;<% end %>
                 </li>
             <% end %>
         </ul>
     </div>





    </div>
</div>