config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations'}

  root 'home#index'
  get '/home/index'
  get '/home/about'

  resources :posts, :except => [:index] do
    collection do
      get 'list/:id' => 'posts#list', as: 'list'
    end
    resources :comments, module: :posts, shallow: true
  end

  resources :playgrounds, :except => [:index] do
    collection do
      resources :ideas, :except => [:index] do
        collection do
          get 'list/:id' => 'ideas#list', as: 'list'
        end
        resources :comments, module: :ideas, shallow: true
      end

      resources :scraps, :except => [:index] do
        collection do
          get 'list/:id' => 'scraps#list', as: 'list'
          get 'members/:id' => 'scraps#members', as: 'members'
        end
        get 'team/:id' => 'scraps#team', as: 'team'
        resources :comments, module: :scraps, shallow: true
      end

      get 'friends'
      get 'list/:id' => 'playgrounds#list', as: 'list'
    end
    resources :comments, module: :playgrounds, shallow: true
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	has_many :comments, as: :commentable, dependent: :destroy

	validates :title, :presence => true
	validates :context, :presence => true

end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
	before_action :set_commentable, only: [:create]
	private
		def set_commentable
			@commentable = Post.find(params[:post_id])
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except:[:show, :list]

  def list
    @post_all = Post.order("created_at DESC")
    @post = @post_all.limit(10).offset(10*params[:id].to_i)
    @count = @post_all.count
  end

  def show
  	@post = Post.find(params[:id])
    @post.hits+=1
    @post.save
  end

  def new

    if current_user.admin==false
      redirect_to root_path
    end

  	@post = Post.new

  end

  def create

    if current_user.admin==false
      redirect_to root_path
    end

  	post = Post.new
  	post.user_id = current_user.id
  	post.title = params[:post][:title]
  	post.context = params[:post][:context]
  	post.save

  	redirect_to post_path(post.id)

  end

  def edit

    if current_user.admin==false
      redirect_to root_path
    end

  	@post = Post.find(params[:id])

  end

  def update

    if current_user.admin==false
      redirect_to root_path
    end

  	post = Post.find(params[:id])
  	post.user_id = current_user.id
  	post.title = params[:post][:title]
  	post.context = params[:post][:context]
  	post.save

  	redirect_to post_path(post.id)

  end

  def destroy

    if current_user.admin==false
      redirect_to root_path
    end

  	post = Post.find(params[:id])
  	post.destroy

  	redirect_to root_path

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/post-work.png')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>글 수정</h1>
                    <hr class="small">
                    <span class="subheading">글을 수정합니다.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container" style="text-align: center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= bootstrap_form_for(@post) do |f| %>
	            <div class="field">
	              <%= f.text_field :title, autofocus: true, label:"제목" %>
	            </div>

	            <!-- <div class="field">
	            </div> -->

				<div class="field">
	              <%= f.text_area :context, label:"내용", style:"resize: none", rows: 15 %>
	            </div>

	            <div class="actions">
	              <%= f.submit "수정하기" %>
	            </div>
	        <% end %>
	    </div>
	</div>
</div>

app/views/posts/list.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/post.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>공지사항</h1>
                    <hr class="small">
                    <span class="subheading">알려드립니다.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="text-center">
                <%= "총 "+(((@count-1)/10)+1).to_s+"장 중, "+(params[:id].to_i+1).to_s+"번째 장"%>
            </div>
            <hr class="small primary">
            <% @post.each do |p| %>
            <div class="post-preview">
                <%= link_to post_path(p.id) do %>
                    <h2 class="post-title">
                        <%= p.title %>
                    </h2>
                <% end %>
                <!--<h3 class="post-subtitle">

                    </h3> -->
                </a>
                <p class="post-meta"><%= link_to "#{p.user.name}", members_scraps_path(p.user.id), style:"font-style:normal" %> 올림, <%= p.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일 %H시 %M분") %>, <%= p.hits %>번 읽힘. 댓글 <%= p.comments.count %>개.</p>
            </div>
            <hr>
            <% end %>

            <!-- Pager -->
            <ul class="pager">
                <%if params[:id].to_i>0%>
                    <li class="previous">
                        <%= link_to list_posts_path(params[:id].to_i-1) do %>&larr; 이전<% end %>
                    </li>
                <% else %>
                    <li class="previous disabled">
                        <a>&larr; 이전</a>
                    </li>
                <% end %>

                <%if params[:id].to_i==(@count-1)/10%>
                    <li class="next disabled">
                        <a>다음 &rarr;</a>
                    </li>
                <% else %>
                    <li class="next">
                        <%= link_to list_posts_path(params[:id].to_i+1) do %>다음 &rarr;<% end %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/post-work.png')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>글쓰기</h1>
                    <hr class="small">
                    <span class="subheading">무엇을 말하고 싶나요?</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container" style="text-align: center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= bootstrap_form_for [@post] do |f| %>
	            <div class="field">
	              <%= f.text_field :title, autofocus: true, label:"제목", :required => true %>
	            </div>
	            
				<div class="field">
	              <%= f.text_area :context, label:"내용", style:"resize: none", rows: 15, :required => true %>
	            </div>

	            <div class="actions">
	              <%= f.submit "Write" %>
	            </div>
	        <% end %>
	    </div>
	</div>
</div>

app/views/posts/show.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= image_url('bg/post.jpg')%>')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1><%= @post.title %></h1>
                    <!-- <h2 class="subheading">  </h2> -->
                    <span class="meta"><%= link_to "#{@post.user.name}", members_scraps_path(@post.user.id), style:"font-style:normal" %> 올림, <%= @post.created_at.in_time_zone(9).strftime("%Y년 %m월 %d일, %H시 %M분 %S초") %>, <%= @post.hits %>번 읽힘.</span>
                    <br>
                    <% if user_signed_in? %>
                        <% if @post.user.id == current_user.id %>
                            <%= form_tag edit_post_path, method: "get" do %>
                                <button type="submit" class="btn btn-primary col-lg-2" style="margin: 2px">수정</button>
                            <% end %>
                            <%= form_tag "/post/#{@post.id}", method: "delete" do %>
                                <button type="submit" class="btn btn-danger col-lg-2" style="margin: 2px" data-confirm="삭제하나요?">삭제</button>
                            <% end %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p style="padding-bottom: 30px">
                    <% unless @post.context.nil? %>
                        <%= @post.context.gsub("\r\n","<br>").html_safe %>
                    <% end %>
                </p>

                <hr>

                <div>
                    <% @post.comments.each do |r|%>
                    <div class="row">
                        <div class="col-lg-8">
                            <h4><%= link_to "#{r.user.name}", members_scraps_path(r.user.id), style:"font-style:normal" %></h4>
                            <h6><%= r.updated_at.in_time_zone(9).strftime("%Y년 %m월 %d일, %H시 %M분 %S초")%></h6>
                            <p><%= r.context %></p>
                        </div>

                        <% if user_signed_in? %>
                            <% if r.user.id == current_user.id %>
                                <div class="col-lg-4">
                                    <%= form_tag comment_path(r.id), method: "delete" do %>
                                        <%= hidden_field_tag(:reply_id, r.id) %>
                                        <button type="submit" class="btn btn-danger" style="float:right; margin: 2px" data-confirm="삭제하나요?">삭제</button>
                                    <% end %>
                                </div>
                            <% end %>
                        <% end %>
                    </div>
                    <hr>
                    <% end %>
                </div>


                <div>
                    <%= bootstrap_form_for [@post, @post.comments.new] do |f| %>
                        <% if user_signed_in? %>
                            <div class="field">
                                <%= hidden_field_tag(:post_id, @post.id) %>
                                <%= f.text_area :context, label: "댓글", style:"resize: none", rows: 4, :required => true %>
                            </div>
                        <% else %>
                            <fieldset disabled>
                                <div class="field">
                                    <%= hidden_field_tag(:post_id, @post.id) %>
                                    <%= f.text_area :context, label: "댓글", style:"resize: none", rows: 4, :required => true%>
                                </div>
                            </fieldset>
                        <%end %>

                        <div class="actions">
                            <%= f.submit "댓글쓰기" %>
                        </div>
                    <% end %>

                </div>


            </div>

        </div>
    </div>
</article>